CREATE TABLE `lawn_care_leads` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`source` text DEFAULT 'manual' NOT NULL,
	`external_id` text,
	`customer_name` text NOT NULL,
	`email` text,
	`phone` text,
	`address` text,
	`city` text,
	`state` text,
	`zip` text,
	`service_type` text NOT NULL,
	`property_type` text,
	`recurring` integer DEFAULT 0 NOT NULL,
	`urgency` text DEFAULT 'normal' NOT NULL,
	`budget_cents` integer,
	`preferred_date` text,
	`preferred_time_window` text,
	`message` text NOT NULL,
	`normalized_summary` text NOT NULL,
	`score` integer NOT NULL,
	`score_label` text NOT NULL,
	`score_reasons` text NOT NULL,
	`next_best_action` text NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`raw_payload` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
